/**
 * Created by Барашики on 26.03.2017.
 */

export const DELETE_ACTION = 'DELETE_ACTION';
export const EDIT_ACTION = 'EDIT_ACTION';
export const FILTER_ACTION = 'FILTER_ACTION';
export const REQUEST_ACTION = 'REQUEST_ACTIONS';
export const RECEIVE_ACTIONS = 'RECEIVE_ACTIONS';
export const RECEIVE_ACTION = 'RECEIVE_ACTION';
export const DELETING_ACTION = 'DELETING_ACTION';
export const ACTION_DELETED = 'ACTION_DELETED';
export const SET_CURRENT_ACTION = 'SET_CURRENT_ACTION';
export const ACTION_SAVED = 'ACTION_SAVED';
export const VALIDATE_ACTION = 'VALIDATE_ACTION';
export const UPDATE_ACTIONS_FILTER = 'UPDATE_ACTIONS_FILTER';

export const RECEIVE_ZONES = 'RECEIVE_ZONES';
export const REQUEST_ZONES = 'REQUEST_ZONES';
export const RECEIVE_USAGES = 'RECEIVE_USAGES';
export const REQUEST_USAGES = 'REQUEST_USAGES';


export const CREATE_ITEM = 'CREATE_ITEM';
export const EDIT_ITEMS = 'EDIT_ITEMS';
export const FILTER_ITEMS = 'FILTER_ITEMS';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const VALIDATE_ITEM = 'VALIDATE_ITEM';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const SAVE_ITEM = 'SAVE_ITEM';
export const UPDATE_ITEMS_FILTER = 'UPDATE_ITEMS_FILTER';
export const SET_ITEMS_LOADING = 'SET_ITEMS_LOADING';
export const START_IMPORT = 'START_IMPORT';
export const STOP_IMPORT = 'STOP_IMPORT';
export const ITEM_SAVED = 'ITEM_SAVED';


export const OPEN_IMPORT_DIALOG = 'OPEN_IMPORT_DIALOG';
export const CLOSE_IMPORT_DIALOG = 'CLOSE_IMPORT_DIALOG';


export const CREATE_ZONE = 'CREATE_ZONE';
export const OPEN_ZONE = 'OPEN_ZONE';
export const EDIT_ZONE = 'EDIT_ZONE';
export const USAGE_OPENED = 'USAGE_OPENED';
export const USAGE_CLOSED = 'USAGE_CLOSED';
export const USAGE_CLEARED = 'USAGE_CLEARED';
export const USAGES_LOADED = 'USAGES_LOADED';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const LOGIN = 'LOGIN';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const LOGIN_IN_PROCESS = 'LOGIN_IN_PROCESS';
export const LOGIN_CHANGED = 'LOGIN_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGOUT = 'LOGOUT';
export const OPEN_INVENTORIZATION_DIALOG = 'OPEN_INVENTORIZATION_DIALOG';
export const CLOSE_INVENTORIZATION_DIALOG = 'CLOSE_INVENTORIZATION_DIALOG';
export const INVENTORIZATION_SELECTED = 'INVENTORIZATION_SELECTED';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const USERS_RECEIVED = 'USERS_RECEIVED';
export const FETCH_USERS = 'FETCH_USERS';
export const DELETE_USER = 'DELETE_USER';
export const USER_DELETED = 'USER_DELETED';
export const USER_SAVED = 'USER_SAVED ';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const VALIDATE_USER = 'VALIDATE_USER';

export const REPORT_LOAD_INV3 = 'REPORT_LOAD_INV3';
export const REPORT_LOAD_IN_PROCESS = 'REPORT_LOAD_IN_PROCESS';
export const REPORT_LOAD_FINISHED = 'REPORT_LOAD_FINISHED';

export const RECEIVE_RESTS = 'RECEIVE_RESTS';
export const REQUEST_RESTS = 'REQUEST_RESTS';

export const COMPANY_LOADING = 'COMPANY_LOADING';
export const COMPANY_LOADED = 'COMPANY_LOADED';
export const COMAPNY_VALIDATED = 'COMAPNY_VALIDATED';
export const VALIDATE_COMPANY = 'VALIDATE_COMPANY';
export const COMPANY_SAVING = 'COMPANY_SAVING';
export const COMPANY_SAVED = 'COMPANY_SAVED';
export const HIDE_COMPANY_LOADING = 'HIDE_COMPANY_LOADING';
export const COMPANY_LIST_LOADED = 'COMPANY_LIST_LOADED';
export const COMPANY_LIST_LOADING = 'COMPANY_LIST_LOADING';
export const VALIDATE_DATA = 'VALIDATE_DATA';
export const DATA_VALIDATED = 'DATA_VALIDATED';
export const PARSE_DATA = 'PARSE_DATA';
export const DATA_IMPORTED = 'DATA_IMPORTED';


export const INVENTORIZATION_LOADING = 'INVENTORIZATION_LOADING';
export const INVENTORIZATION_LOADED = 'INVENTORIZATION_LOADED';
export const INVENTORIZATION_VALIDATED = 'COMAPNY_VALIDATED';
export const VALIDATE_INVENTORIZATION = 'VALIDATE_INVENTORIZATION';
export const INVENTORIZATION_SAVING = 'INVENTORIZATION_SAVING';
export const INVENTORIZATION_SAVED = 'INVENTORIZATION_SAVED';
export const HIDE_INVENTORIZATION_LOADING = 'HIDE_INVENTORIZATION_LOADING';
export const INVENTORIZATION_LIST_LOADED = 'INVENTORIZATION_LIST_LOADED';
export const INVENTORIZATION_LIST_LOADING = 'INVENTORIZATION_LIST_LOADING';
export const VALIDATE_RESTS_DATA = 'VALIDATE_DATA';
export const RESTS_DATA_VALIDATED = 'DATA_VALIDATED';
export const PARSE_RESTS_DATA = 'PARSE_DATA';
export const RESTS_DATA_IMPORTED = 'DATA_IMPORTED';
export const OPEN_IMPORT_RESTS_DIALOG = 'OPEN_IMPORT_RESTS_DIALOG';
export const CLOSE_IMPORT_RESTS_DIALOG = 'CLOSE_IMPORT_RESTS_DIALOG';
export const START_RESTS_IMPORT = 'START_RESTS_IMPORT';

export const RECEIVE_DICTIONARY = 'RECEIVE_DICTIONARY';
export const REQUEST_DICTIONARY = 'REQUEST_DICTIONARY';
export const LOAD_MORE_DICTIONARY_ITEMS = 'LOAD_MORE_DICTIONARY_ITEMS';
export const UPDATE_DICTIONARY_ITEMS_FILTER = 'UPDATE_DICTIONARY_ITEMS_FILTER';
export const SET_DICTIONARY_ITEMS_LOADING = 'SET_DICTIONARY_ITEMS_LOADING';
export const FILTER_DICTIONARY_ITEMS = 'FILTER_DICTIONARY_ITEMS';
export const SHOW_DICTIONARY_LOADING = 'SHOW_DICTIONARY_LOADING';
export const HIDE_DICTIONARY_LOADING = 'HIDE_DICTIONARY_LOADING';