/**
 * Created by Барашики on 26.03.2017.
 */

export const DELETE_ACTION = 'DELETE_ACTION';
export const EDIT_ACTION = 'EDIT_ACTION';
export const FILTER_ACTION = 'FILTER_ACTION';
export const REQUEST_ACTION = 'REQUEST_ACTIONS';
export const RECEIVE_ACTION = 'RECEIVE_ACTION';
export const DELETING_ACTION = 'DELETING_ACTION';
export const ACTION_DELETED = 'ACTION_DELETED';
export const SET_CURRENT_ACTION = 'SET_CURRENT_ACTION';
export const ACTION_SAVED = 'ACTION_SAVED';
export const VALIDATE_ACTION = 'VALIDATE_ACTION';
export const UPDATE_ACTIONS_FILTER = 'UPDATE_ACTIONS_FILTER';

export const RECEIVE_ZONES = 'RECEIVE_ZONES';
export const REQUEST_ZONES = 'REQUEST_ZONES';


export const CREATE_ITEM = 'CREATE_ITEM';
export const EDIT_ITEMS = 'EDIT_ITEMS';
export const FILTER_ITEMS = 'FILTER_ITEMS';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const VALIDATE_ITEM = 'VALIDATE_ITEM';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const SAVE_ITEM = 'SAVE_ITEM';
export const UPDATE_ITEMS_FILTER = 'UPDATE_ITEMS_FILTER';
export const SET_ITEMS_LOADING = 'SET_ITEMS_LOADING';
export const START_IMPORT = 'START_IMPORT';
export const STOP_IMPORT = 'STOP_IMPORT';
export const ITEM_SAVED = 'ITEM_SAVED';


export const OPEN_IMPORT_DIALOG = 'OPEN_IMPORT_DIALOG';
export const CLOSE_IMPORT_DIALOG = 'CLOSE_IMPORT_DIALOG';


export const CREATE_ZONE = 'CREATE_ZONE';
export const OPEN_ZONE = 'OPEN_ZONE';
export const EDIT_ZONE = 'EDIT_ZONE';
export const ZONE_OPENED = 'ZONE_OPENED';
export const ZONE_CLOSED = 'ZONE_CLOSED';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const LOGIN = 'LOGIN';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const LOGIN_IN_PROCESS = 'LOGIN_IN_PROCESS';
export const LOGIN_CHANGED = 'LOGIN_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGOUT = 'LOGOUT';
export const OPEN_INVENTORIZATION_DIALOG = 'OPEN_INVENTORIZATION_DIALOG';
export const CLOSE_INVENTORIZATION_DIALOG = 'CLOSE_INVENTORIZATION_DIALOG';
export const INVENTORIZATION_SELECTED = 'INVENTORIZATION_SELECTED';
